package gui.channelGUI;

import javax.swing.JFrame;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.awt.FlowLayout;
import javax.swing.SwingConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joshua
 */
public class CreateChannelFrame extends javax.swing.JFrame {
    private static CreateChannelFrame instance = null;
    private static JFrame parent;
    private JTextField textField;
    /**
     * Creates new form ChannelFrame
     */
    private CreateChannelFrame() {
        initComponents();
    }
    
    public static CreateChannelFrame getInstance(JFrame parent){
        if(instance == null){
            instance = new CreateChannelFrame();
            CreateChannelFrame.parent = parent;
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        
        JLabel lblNewLabel = new JLabel("Channel Name: ");
        getContentPane().add(lblNewLabel);
        
        textField = new JTextField();
        getContentPane().add(textField);
        textField.setColumns(23);
        
        JButton btnNewButton = new JButton("Create");
        btnNewButton.setVerticalAlignment(SwingConstants.BOTTOM);
        getContentPane().add(btnNewButton);
        
        JButton btnNewButton_1 = new JButton("Cancel");
        btnNewButton_1.setVerticalAlignment(SwingConstants.BOTTOM);
        getContentPane().add(btnNewButton_1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
