package gui.channelGUI;

import gui.ClientGUI;

import javax.swing.JFrame;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JButton;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.SwingConstants;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joshua
 */
public class LeaveChannelFrame extends javax.swing.JFrame {
    private static LeaveChannelFrame instance = null;
    private static ClientGUI parent;
    private JTextField textField;
    /**
     * Creates new form ChannelFrame
     */
    private LeaveChannelFrame() {
        initComponents();
    }
    
    public static LeaveChannelFrame getInstance(ClientGUI parent){
        if(instance == null){
            instance = new LeaveChannelFrame();
            LeaveChannelFrame.parent = parent;
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	 setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        
        JLabel lblNewLabel = new JLabel("Channel Name: ");
        getContentPane().add(lblNewLabel);
        
        textField = new JTextField();
        textField.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyPressed(KeyEvent e) {
        		if(e.getKeyCode()==KeyEvent.VK_ENTER){
        			try {
    					parent.ch.sendToServer("#leaveChannel "+textField.getText());
    					dispose();
    				} catch (IOException e1) {
    					e1.printStackTrace();
    				}
        		}
        	}
        });
        getContentPane().add(textField);
        textField.setColumns(23);
        
        JButton btnNewButton = new JButton("Leave");
        btnNewButton.setVerticalAlignment(SwingConstants.BOTTOM);
        getContentPane().add(btnNewButton);
        
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		//attempt to join selected channel
        		try {
					parent.ch.sendToServer("#leaveChannel "+textField.getText());
					dispose();
				} catch (IOException e1) {
					e1.printStackTrace();
				}
        	}
        });
        
        JButton btnNewButton_1 = new JButton("Cancel");
        btnNewButton_1.setVerticalAlignment(SwingConstants.BOTTOM);
        getContentPane().add(btnNewButton_1);
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		dispose();
        	}
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents
}
